version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - taskmanager_net

  backend:
    container_name: taskmanager
    build:
        context: ./backend
        dockerfile: Dockerfile
        args:
            - APP_ENV=${APP_ENV}
    ports:
        - '${APP_PORT:-8880}:80'
        - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
        - APP_ENV=${APP_ENV}
        - CONTAINER_ROLE=app
        - TZ=Africa/Lagos
    working_dir: /var/www/html
    volumes:
        - './backend:/var/www/html'
        - './.env:/var/www/html/.env'
    networks:
        - taskmanager_net
    depends_on:
        - mysql
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
        - '${DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
        - 'taskmanager-mysql:/var/lib/mysql'
        - './backend/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
        - taskmanager_net
    healthcheck:
        test:
            - CMD
            - mysqladmin
            - ping
            - '-p${DB_PASSWORD}'
        retries: 3
        timeout: 5s
networks:
  taskmanager_net:
      driver: bridge
volumes:
  taskmanager-mysql:
      driver: local